//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Registro
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Ingrese su Nombre")]
        public string Nombre { get; set; }
        [Required]
        [Display(Name = "Ingrese su Apellido")]
        public string Apellido { get; set; }
        [Required]
        [Display(Name = "Ingrese su Telefono")]
        public string Telefono { get; set; }
        [Required]
        [Display(Name = "Ingrese su Sector")]
        public string Sector { get; set; }
    }
}
